### ISSUE TITLE
Le texte modifié dans la section d'un plan ne s'affiche pas

### ISSUE THREAD

**Issue by aldaitzwild** [WildCodeSchool/2022-03-php-Lyon-P3-Usedge#78]
Ce que je rentre : 
![image](https://user-images.githubusercontent.com/79696812/179731125-a34ee901-b7c0-4c5e-bbe2-b7db4e6ba3f8.png)

Ce que j'obtiens : 
![image](https://user-images.githubusercontent.com/79696812/179731214-6c43d110-c96d-4555-a04c-52c6b0c74526.png)

**Comment by christophercuzin** [comment]
pour que la modification soit validé il faut appuyer sur entrer avant la validation du formulaire
